version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: dev
    restart: always
    ports:
      - 3308:3306
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: dev
      TZ: Asia/Seoul
    volumes:
      - ./db:/var/lib/mysql
